#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
#

# Error handling function
handle_error() {
    echo "Error occurred on line $1"
    exit 1
}

trap 'handle_error $LINENO' ERR

echo -e "Updating and installing Nginx.\n"
# Check if Nginx is already installed
if ! command -v nginx &> /dev/null; then
    sudo apt-get update -y -qq
    sudo apt-get install nginx -y
fi

echo -e "\nSetting up some minor stuff.\n"

# Set ownership and permissions for the web directory
sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www/html

# Backup default index if it exists
if [[ -f /var/www/html/index.nginx-debian.html ]]; then
    cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
fi

# Creating new index
echo -e "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html >/dev/null

# Restarting nginx
sudo service nginx restart

echo -e "\nCompleted. ✅\n"
