#!/bin/bash
# Configures an Nginx server to listen on port 80.

sudo sed -i 's/^.*80.*/listen 80 default_server;/' /etc/nginx/sites-available/default
sudo service nginx restart
echo "" | sudo dd status=none of=/run/nginx.pid

