#!/usr/bin/env bash
#displays best school 10times using while loop and also hi on 9th line

counter=1
while [ $counter -le 10 ] 
do
  if [ $counter -eq 9 ]
    then
      echo "Hi"
    fi
    echo "Best School"
    ((counter++))
done
